linters-settings:
  cyclop:
    max-complexity: 20
  gocognit:
    min-complexity: 50
  goconst:
    min-occurrences: 8
  funlen:
    lines: 150
    statements: 60
  wrapcheck:
    ignorePackageGlobs:
      - github.com/gofiber/fiber/v2
      - github.com/thiago-felipe-99/mail/publisher/*
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
linters:
  enable:
    - errcheck
    - ineffassign
    - typecheck
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    # - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    # - exhaustruct
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - grouper
    - importas
    - interfacebloat
    - ireturn
    - lll
    - maintidx
    - makezero
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    # - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    # - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - tagliatelle
    - tenv
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
